spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/promoguard
    username: promoguard
    password: promoguard

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9094

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/PromoGuard

  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true

app:
  keycloak:
    client-id: promoguard-web

logging:
  level:
    org:
      springframework:
        security: DEBUG

springdoc:
  swagger-ui:
    oauth:
      client-id: promoguard-web
      use-pkce-with-authorization-code-grant: true